site_name: HTML to JSON Docs
site_url: https://html-to-json.hightower.space/
repo_url: https://github.com/fhightower/html-to-json
repo_name: html-to-json
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: deep orange
      accent: deep orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: deep orange
      accent: deep orange
  font: false
  icon:
    logo: material/code-json
  features:
    - navigation.instant
    - navigation.top
    - header.autohide
    - toc.integrate
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - toc:
      permalink: true
nav:
    - Home: index.md
    - Interactive Demo: demo.md
    - Quick Start: quick-start.md
    - Developer Docs: development.md
